### alle Schulen
GET http://localhost:8081/schule

### alle Oberschulen
GET http://localhost:8081/schule/bySchulform/Oberschule

### alle Grundschulen
GET http://localhost:8081/schule/bySchulform/Grundschule
Accept: application/json

### Schule mit einer Schul-ID
GET http://localhost:8081/schule/bySchulId/schule_1234
Accept: application/json

### eine Schule mit Klasse und Fach hinzufügen
POST http://localhost:8081/schule
Content-Type: application/json

{
  "name": "Meine Schule",
  "schulId": "schule_1234",
  "schulform": "Grundschule",
  "klassen": [
    {
      "bezeichnung": "1b",
      "klassenstufe": 1,
      "unterrichtsfachList": [
        {
          "name": "Sport",
          "anzahlProWoche": 2
        }
      ]
    }
  ]
}


### eine Schule löschen
DELETE http://localhost:8081/schule/schule_1234

### alle Klassen
GET http://localhost:8081/klasse